'use client';

import { useEffect, useState, type FormEvent } from 'react';
import { Activity, AlertTriangle, BarChart3, Coins, FileText, LogOut, Search, ShieldAlert, Users, WalletCards } from 'lucide-react';
import { adminFetch, clearSession, getSession, login, type Admin } from '@/lib/api';

type View = 'dashboard' | 'reports' | 'users' | 'tokens' | 'finance' | 'audit';
type Dashboard = { counts: Record<string, number>; liabilities: { availableUsdtRaw: string }; health: { indexerLastProcessedBlock: string | null } };
type Report = { id: string; targetType: string; targetId: string; reason: string; status: string; reportCount: number; priority: string; createdAt: string };
type User = { id: string; email: string | null; primaryWalletAddress: string | null; authType: string; createdAt: string; profile: { usernameDisplay: string; username: string } | null; balances: Array<{ asset: string; available: string }> };
type Token = { mint: string; symbol: string; name: string; creator: string; status: string; currentSupply: string; supplyCap: string; graduationThreshold: string; createdAt: string };
type Withdrawal = { id: string; userWallet: string; destination: string; amount: string; asset: string; status: string; createdAt: string };
type Audit = { id: string; action: string; targetType: string | null; targetId: string | null; createdAt: string; adminUser: { displayName: string; role: string } };

const nav: Array<{ id: View; label: string; icon: typeof Activity }> = [
  { id: 'dashboard', label: 'Dashboard', icon: BarChart3 }, { id: 'reports', label: 'Reports', icon: ShieldAlert },
  { id: 'users', label: 'Users', icon: Users }, { id: 'tokens', label: 'Tokens', icon: Coins },
  { id: 'finance', label: 'Finance', icon: WalletCards }, { id: 'audit', label: 'Audit log', icon: FileText },
];

export default function AdminApp() {
  const [session, setSession] = useState<{ token: string; admin: Admin } | null>(null);
  const [view, setView] = useState<View>('dashboard');
  useEffect(() => setSession(getSession()), []);
  if (!session) return <Login onSuccess={setSession} />;
  const signOut = () => { clearSession(); setSession(null); };
  return <div className="admin-shell"><aside className="sidebar"><div className="brand">LIMIANCE <span>OPS</span></div><nav className="nav">{nav.map(({ id, label, icon: Icon }) => <button key={id} className={view === id ? 'active' : ''} onClick={() => setView(id)}><Icon size={17} /><span>{label}</span></button>)}</nav></aside><main className="main"><header className="topbar"><h1>{nav.find((item) => item.id === view)?.label}</h1><div className="admin-meta">{session.admin.displayName}<br /><span>{session.admin.role}</span> <button className="ghost" onClick={signOut}><LogOut size={14} /></button></div></header><div className="content"><ViewContent view={view} /></div></main></div>;
}

function Login({ onSuccess }: { onSuccess: (session: { token: string; admin: Admin }) => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { onSuccess(await login(email, password)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to sign in'); } finally { setBusy(false); } };
  return <div className="login-page"><form className="login" onSubmit={submit}><div className="brand" style={{ padding: 0, marginBottom: 28 }}>LIMIANCE <span>OPS</span></div><h1>Admin sign in</h1><p>Restricted operations console.</p><label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required autoComplete="username" /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required autoComplete="current-password" /></label>{error && <div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy ? 'Signing in...' : 'Sign in'}</button></form></div>;
}

function ViewContent({ view }: { view: View }) { if (view === 'dashboard') return <DashboardView />; if (view === 'reports') return <ReportsView />; if (view === 'users') return <UsersView />; if (view === 'tokens') return <TokensView />; if (view === 'finance') return <FinanceView />; return <AuditView />; }

function DashboardView() { const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState(''); useEffect(() => { adminFetch<Dashboard>('/admin/dashboard').then(setData).catch((e) => setError(e.message)); }, []); if (error) return <div className="error">{error}</div>; if (!data) return <div className="empty">Loading dashboard...</div>; const cards = [['Users', data.counts.users], ['Tokens', data.counts.tokens], ['Trades 24h', data.counts.trades24h], ['Open reports', data.counts.openReports], ['Pending withdrawals', data.counts.pendingWithdrawals], ['Comments', data.counts.comments], ['Profiles', data.counts.profiles], ['Available USDT', (Number(data.liabilities.availableUsdtRaw) / 1e6).toFixed(2)]]; return <><div className="cards">{cards.map(([label, value]) => <div className="card" key={String(label)}><div className="card-label">{label}</div><div className="card-value">{value}</div></div>)}</div><section className="card"><div className="section-title"><h2>System health</h2><Activity size={17} color="var(--green)" /></div><div className="muted">Indexer last processed block: {data.health.indexerLastProcessedBlock ?? 'No state recorded'}</div></section></>; }

function ReportsView() { const [reports, setReports] = useState<Report[]>([]); const [status, setStatus] = useState(''); const load = () => adminFetch<{ reports: Report[] }>(`/admin/reports${status ? `?status=${status}` : ''}`).then((d) => setReports(d.reports)); useEffect(() => { void load(); }, [status]); const update = async (id: string, next: string) => { await adminFetch(`/admin/reports/${id}`, { method: 'PATCH', body: JSON.stringify({ status: next, resolution: next === 'dismissed' ? 'Reviewed and dismissed' : undefined }) }); void load(); }; return <><div className="toolbar"><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option><option value="open">Open</option><option value="reviewing">Reviewing</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select></div><section className="table-wrap"><table><thead><tr><th>Priority</th><th>Target</th><th>Reason</th><th>Reports</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>{reports.map((r) => <tr key={r.id}><td><span className={`pill ${r.priority}`}>{r.priority}</span></td><td>{r.targetType} <span className="muted">{r.targetId.slice(0, 14)}...</span></td><td>{r.reason}</td><td>{r.reportCount}</td><td>{r.status}</td><td>{new Date(r.createdAt).toLocaleString()}</td><td><select value={r.status} onChange={(e) => void update(r.id, e.target.value)}><option value="open">Open</option><option value="reviewing">Reviewing</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select></td></tr>)}</tbody></table>{reports.length === 0 && <div className="empty">No reports found.</div>}</section></>; }

function UsersView() { const [users, setUsers] = useState<User[]>([]); const [search, setSearch] = useState(''); const load = () => adminFetch<{ users: User[] }>(`/admin/users${search ? `?search=${encodeURIComponent(search)}` : ''}`).then((d) => setUsers(d.users)); useEffect(() => { void load(); }, []); return <><div className="toolbar"><input placeholder="Search email or wallet" value={search} onChange={(e) => setSearch(e.target.value)} /><button className="primary" onClick={() => void load()}><Search size={14} /> Search</button></div><section className="table-wrap"><table><thead><tr><th>Identity</th><th>Wallet</th><th>Auth</th><th>Profile</th><th>Balance</th><th>Created</th></tr></thead><tbody>{users.map((u) => <tr key={u.id}><td>{u.email ?? <span className="muted">Wallet user</span>}</td><td>{u.primaryWalletAddress ?? '-'}</td><td>{u.authType}</td><td>{u.profile?.usernameDisplay ? `@${u.profile.usernameDisplay}` : 'Not onboarded'}</td><td>{u.balances.map((b) => `${(Number(b.available) / 1e6).toFixed(2)} ${b.asset.slice(0, 6)}`).join(', ') || '0'}</td><td>{new Date(u.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></section></>; }

function TokensView() { const [tokens, setTokens] = useState<Token[]>([]); useEffect(() => { adminFetch<{ tokens: Token[] }>('/admin/tokens').then((d) => setTokens(d.tokens)); }, []); return <section className="table-wrap"><table><thead><tr><th>Token</th><th>Creator</th><th>Status</th><th>Supply</th><th>Graduation</th><th>Created</th></tr></thead><tbody>{tokens.map((t) => <tr key={t.mint}><td><b>${t.symbol}</b><br /><span className="muted">{t.name}</span></td><td>{t.creator}</td><td><span className="pill">{t.status}</span></td><td>{Number(t.currentSupply).toLocaleString()} / {Number(t.supplyCap).toLocaleString()}</td><td>{Number(t.graduationThreshold).toLocaleString()}</td><td>{new Date(t.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></section>; }

function FinanceView() { const [rows, setRows] = useState<Withdrawal[]>([]); useEffect(() => { adminFetch<{ withdrawals: Withdrawal[] }>('/admin/finance/withdrawals').then((d) => setRows(d.withdrawals)); }, []); return <section className="table-wrap"><table><thead><tr><th>Status</th><th>User</th><th>Destination</th><th>Amount</th><th>Asset</th><th>Created</th></tr></thead><tbody>{rows.map((w) => <tr key={w.id}><td><span className={`pill ${w.status === 'pending' ? 'review' : ''}`}>{w.status}</span></td><td>{w.userWallet}</td><td>{w.destination}</td><td>{(Number(w.amount) / 1e6).toFixed(2)}</td><td>{w.asset}</td><td>{new Date(w.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{rows.length === 0 && <div className="empty">No withdrawals found.</div>}</section>; }

function AuditView() { const [logs, setLogs] = useState<Audit[]>([]); useEffect(() => { adminFetch<{ logs: Audit[] }>('/admin/audit-logs').then((d) => setLogs(d.logs)); }, []); return <section className="table-wrap"><table><thead><tr><th>Action</th><th>Admin</th><th>Target</th><th>Time</th></tr></thead><tbody>{logs.map((l) => <tr key={l.id}><td>{l.action}</td><td>{l.adminUser.displayName} <span className="muted">({l.adminUser.role})</span></td><td>{l.targetType ?? '-'} {l.targetId ?? ''}</td><td>{new Date(l.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{logs.length === 0 && <div className="empty">No audit entries found.</div>}</section>; }
