'use client';

import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { Activity, BarChart3, Coins, FileText, LogOut, Search, ShieldAlert, UserCog, Users, WalletCards } from 'lucide-react';
import { adminFetch, clearSession, getSession, login, type Admin } from '@/lib/api';

type View = 'dashboard' | 'reports' | 'users' | 'tokens' | 'finance' | 'audit' | 'admins';
type Dashboard = { counts: Record<string, number>; liabilities: { availableUsdtRaw: string }; health: { indexerLastProcessedBlock: string | null } };
type Report = { id: string; targetType: string; targetId: string; reason: string; details?: string | null; status: string; reportCount: number; priority: string; createdAt: string };
type User = { id: string; email: string | null; primaryWalletAddress: string | null; authType: string; status: string; createdAt: string; profile: { usernameDisplay: string } | null; balances: Array<{ asset: string; available: string }> };
type Token = { mint: string; symbol: string; name: string; creator: string; status: string; currentSupply: string; supplyCap: string; graduationThreshold: string; createdAt: string };
type Withdrawal = { id: string; userWallet: string; destination: string; amount: string; asset: string; status: string; txHash?: string | null; refundedAt?: string | null; createdAt: string };
type Audit = { id: string; action: string; targetType: string | null; targetId: string | null; createdAt: string; adminUser: { displayName: string; role: string } };
type AdminRow = { id: string; email: string; displayName: string; role: string; status: string; lastLoginAt?: string | null; createdAt: string };

const nav: Array<{ id: View; label: string; icon: typeof Activity; roles?: string[] }> = [
  { id: 'dashboard', label: 'Dashboard', icon: BarChart3 }, { id: 'reports', label: 'Reports', icon: ShieldAlert },
  { id: 'users', label: 'Users', icon: Users }, { id: 'tokens', label: 'Tokens', icon: Coins },
  { id: 'finance', label: 'Finance', icon: WalletCards }, { id: 'audit', label: 'Audit log', icon: FileText },
  { id: 'admins', label: 'Administrators', icon: UserCog, roles: ['super_admin'] },
];

export default function AdminApp() {
  const [session, setSession] = useState<{ token: string; admin: Admin } | null>(null);
  const [view, setView] = useState<View>('dashboard');
  useEffect(() => setSession(getSession()), []);
  if (!session) return <Login onSuccess={setSession} />;
  const allowedNav = nav.filter((item) => !item.roles || item.roles.includes(session.admin.role) || session.admin.role === 'super_admin');
  const signOut = () => { clearSession(); setSession(null); };
  return <div className="admin-shell"><aside className="sidebar"><div className="brand">LIMIANCE <span>OPS</span></div><nav className="nav">{allowedNav.map(({ id, label, icon: Icon }) => <button key={id} className={view === id ? 'active' : ''} onClick={() => setView(id)}><Icon size={17} /><span>{label}</span></button>)}</nav></aside><main className="main"><header className="topbar"><h1>{nav.find((item) => item.id === view)?.label}</h1><div className="admin-meta">{session.admin.displayName}<br /><span>{session.admin.role}</span> <button className="ghost" title="Sign out" onClick={signOut}><LogOut size={14} /></button></div></header><div className="content"><ViewContent view={view} /></div></main></div>;
}

function Login({ onSuccess }: { onSuccess: (session: { token: string; admin: Admin }) => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { onSuccess(await login(email, password)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to sign in'); } finally { setBusy(false); } };
  return <div className="login-page"><form className="login" onSubmit={submit}><div className="brand" style={{ padding: 0, marginBottom: 28 }}>LIMIANCE <span>OPS</span></div><h1>Admin sign in</h1><p>Restricted operations console.</p><label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required autoComplete="username" /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required autoComplete="current-password" /></label>{error && <div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy ? 'Signing in...' : 'Sign in'}</button></form></div>;
}

function ViewContent({ view }: { view: View }) { if (view === 'dashboard') return <DashboardView />; if (view === 'reports') return <ReportsView />; if (view === 'users') return <UsersView />; if (view === 'tokens') return <TokensView />; if (view === 'finance') return <FinanceView />; if (view === 'admins') return <AdminsView />; return <AuditView />; }
function ErrorBox({ error }: { error: string }) { return error ? <div className="error">{error}</div> : null; }
function useAction() { const [error, setError] = useState(''); const run = async (fn: () => Promise<unknown>) => { setError(''); try { await fn(); return true; } catch (e) { setError(e instanceof Error ? e.message : 'Action failed'); return false; } }; return { error, run }; }
function Pager({ page, hasMore, onChange }: { page: number; hasMore: boolean; onChange: (page: number) => void }) { return <div className="pager"><button disabled={page === 0} onClick={() => onChange(page - 1)}>Previous</button><span>Page {page + 1}</span><button disabled={!hasMore} onClick={() => onChange(page + 1)}>Next</button></div>; }

function DashboardView() { const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState(''); useEffect(() => { adminFetch<Dashboard>('/admin/dashboard').then(setData).catch((e) => setError(e.message)); }, []); if (error) return <ErrorBox error={error} />; if (!data) return <div className="empty">Loading dashboard...</div>; const cards = [['Users', data.counts.users], ['Tokens', data.counts.tokens], ['Trades 24h', data.counts.trades24h], ['Open reports', data.counts.openReports], ['Pending withdrawals', data.counts.pendingWithdrawals], ['Comments', data.counts.comments], ['Profiles', data.counts.profiles], ['Available USDT', (Number(data.liabilities.availableUsdtRaw) / 1e6).toFixed(2)]]; return <><div className="cards">{cards.map(([label, value]) => <div className="card" key={String(label)}><div className="card-label">{label}</div><div className="card-value">{value}</div></div>)}</div><section className="card"><div className="section-title"><h2>System health</h2><Activity size={17} color="var(--green)" /></div><div className="muted">Indexer last processed block: {data.health.indexerLastProcessedBlock ?? 'No state recorded'}</div></section></>; }

function ReportsView() { const [reports, setReports] = useState<Report[]>([]); const [status, setStatus] = useState(''); const [page, setPage] = useState(0); const [error, setError] = useState(''); const load = () => adminFetch<{ reports: Report[] }>(`/admin/reports?limit=50&offset=${page * 50}${status ? `&status=${status}` : ''}`).then((d) => setReports(d.reports)).catch((e) => setError(e.message)); useEffect(() => { void load(); }, [status, page]); const update = async (id: string, next: string) => { try { await adminFetch(`/admin/reports/${id}`, { method: 'PATCH', body: JSON.stringify({ status: next, resolution: next === 'dismissed' ? 'Reviewed and dismissed' : undefined }) }); void load(); } catch (e) { setError(e instanceof Error ? e.message : 'Update failed'); } }; const removeComment = async (id: string) => { if (!window.confirm('Remove this reported comment?')) return; try { await adminFetch(`/admin/comments/${id}`, { method: 'DELETE', body: JSON.stringify({ reason: 'Removed from moderation queue' }) }); void load(); } catch (e) { setError(e instanceof Error ? e.message : 'Removal failed'); } }; return <><div className="toolbar"><select value={status} onChange={(e) => { setPage(0); setStatus(e.target.value); }}><option value="">All statuses</option><option value="open">Open</option><option value="reviewing">Reviewing</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select></div><ErrorBox error={error} /><section className="table-wrap"><table><thead><tr><th>Priority</th><th>Target</th><th>Reason</th><th>Reports</th><th>Status</th><th>Details</th><th>Action</th></tr></thead><tbody>{reports.map((r) => <tr key={r.id}><td><span className={`pill ${r.priority}`}>{r.priority}</span></td><td>{r.targetType} <span className="muted">{r.targetId.slice(0, 14)}...</span></td><td>{r.reason}</td><td>{r.reportCount}</td><td>{r.status}</td><td>{r.details || '-'}</td><td><select value={r.status} onChange={(e) => void update(r.id, e.target.value)}><option value="open">Open</option><option value="reviewing">Reviewing</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select>{r.targetType === 'comment' && <button className="small danger" onClick={() => void removeComment(r.targetId)}>Remove</button>}</td></tr>)}</tbody></table>{reports.length === 0 && <div className="empty">No reports found.</div>}<Pager page={page} hasMore={reports.length === 50} onChange={setPage} /></section></>; }

function UsersView() { const [users, setUsers] = useState<User[]>([]); const [search, setSearch] = useState(''); const [page, setPage] = useState(0); const [selected, setSelected] = useState<User | null>(null); const action = useAction(); const load = () => adminFetch<{ users: User[] }>(`/admin/users?limit=50&offset=${page * 50}${search ? `&search=${encodeURIComponent(search)}` : ''}`).then((d) => setUsers(d.users)).catch((e) => action.run(async () => { throw e; })); useEffect(() => { void load(); }, [page]); const setStatus = async (user: User) => { const next = user.status === 'suspended' ? 'active' : 'suspended'; if (!window.confirm(`${next === 'suspended' ? 'Suspend' : 'Reactivate'} this user?`)) return; if (await action.run(() => adminFetch(`/admin/users/${user.id}/status`, { method: 'PATCH', body: JSON.stringify({ status: next, reason: 'Admin console action' }) }))) void load(); }; return <><div className="toolbar"><input placeholder="Search email or wallet" value={search} onChange={(e) => setSearch(e.target.value)} /><button className="primary" onClick={() => { setPage(0); void load(); }}><Search size={14} /> Search</button></div><ErrorBox error={action.error} /><section className="table-wrap"><table><thead><tr><th>Identity</th><th>Wallet</th><th>Auth</th><th>Profile</th><th>Balance</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map((u) => <tr key={u.id}><td>{u.email ?? <span className="muted">Wallet user</span>}</td><td>{u.primaryWalletAddress ?? '-'}</td><td>{u.authType}</td><td>{u.profile?.usernameDisplay ? `@${u.profile.usernameDisplay}` : 'Not onboarded'}</td><td>{u.balances.map((b) => `${(Number(b.available) / 1e6).toFixed(2)} ${b.asset.slice(0, 6)}`).join(', ') || '0'}</td><td><span className={`pill ${u.status}`}>{u.status}</span></td><td><button className="small" onClick={() => setSelected(u)}>Details</button> <button className="small" onClick={() => void setStatus(u)}>{u.status === 'suspended' ? 'Reactivate' : 'Suspend'}</button></td></tr>)}</tbody></table><Pager page={page} hasMore={users.length === 50} onChange={setPage} /></section>{selected && <Detail title="User details" onClose={() => setSelected(null)}><pre>{JSON.stringify(selected, null, 2)}</pre></Detail>}</>; }

function TokensView() { const [tokens, setTokens] = useState<Token[]>([]); const [search, setSearch] = useState(''); const [page, setPage] = useState(0); const action = useAction(); const load = () => adminFetch<{ tokens: Token[] }>(`/admin/tokens?limit=50&offset=${page * 50}${search ? `&search=${encodeURIComponent(search)}` : ''}`).then((d) => setTokens(d.tokens)).catch((e) => action.run(async () => { throw e; })); useEffect(() => { void load(); }, [page]); const toggle = async (token: Token) => { const status = token.status === 'cancelled' ? 'active' : 'cancelled'; if (!window.confirm(`${status === 'cancelled' ? 'Hide' : 'Restore'} this token?`)) return; if (await action.run(() => adminFetch(`/admin/tokens/${encodeURIComponent(token.mint)}/status`, { method: 'PATCH', body: JSON.stringify({ status, reason: 'Admin console action' }) }))) void load(); }; return <><div className="toolbar"><input placeholder="Search symbol, name, or mint" value={search} onChange={(e) => setSearch(e.target.value)} /><button className="primary" onClick={() => { setPage(0); void load(); }}><Search size={14} /> Search</button></div><ErrorBox error={action.error} /><section className="table-wrap"><table><thead><tr><th>Token</th><th>Creator</th><th>Status</th><th>Supply</th><th>Created</th><th>Actions</th></tr></thead><tbody>{tokens.map((t) => <tr key={t.mint}><td><b>${t.symbol}</b><br /><span className="muted">{t.name}</span></td><td>{t.creator}</td><td><span className={`pill ${t.status}`}>{t.status}</span></td><td>{Number(t.currentSupply).toLocaleString()} / {Number(t.supplyCap).toLocaleString()}</td><td>{new Date(t.createdAt).toLocaleDateString()}</td><td><button className="small" onClick={() => void toggle(t)}>{t.status === 'cancelled' ? 'Restore' : 'Hide'}</button></td></tr>)}</tbody></table><Pager page={page} hasMore={tokens.length === 50} onChange={setPage} /></section></>; }

function FinanceView() { const [rows, setRows] = useState<Withdrawal[]>([]); const [status, setStatus] = useState(''); const [page, setPage] = useState(0); const action = useAction(); const load = () => adminFetch<{ withdrawals: Withdrawal[] }>(`/admin/finance/withdrawals?limit=50&offset=${page * 50}${status ? `&status=${status}` : ''}`).then((d) => setRows(d.withdrawals)).catch((e) => action.run(async () => { throw e; })); useEffect(() => { void load(); }, [status, page]); const update = async (row: Withdrawal, next: 'processing' | 'completed' | 'failed') => { const txHash = next === 'completed' ? window.prompt('Blockchain transaction hash:') : undefined; const reason = next === 'failed' ? window.prompt('Failure reason:') || undefined : undefined; if (next === 'completed' && !txHash) return; if (await action.run(() => adminFetch(`/admin/finance/withdrawals/${row.id}`, { method: 'PATCH', body: JSON.stringify({ status: next, txHash, reason }) }))) void load(); }; return <><div className="toolbar"><select value={status} onChange={(e) => { setPage(0); setStatus(e.target.value); }}><option value="">All statuses</option><option value="pending">Pending</option><option value="processing">Processing</option><option value="completed">Completed</option><option value="failed">Failed</option></select></div><ErrorBox error={action.error} /><section className="table-wrap"><table><thead><tr><th>Status</th><th>User</th><th>Destination</th><th>Amount</th><th>Asset</th><th>Created</th><th>Actions</th></tr></thead><tbody>{rows.map((w) => <tr key={w.id}><td><span className={`pill ${w.status}`}>{w.status}</span></td><td>{w.userWallet}</td><td>{w.destination}</td><td>{(Number(w.amount) / 1e6).toFixed(2)}</td><td>{w.asset}</td><td>{new Date(w.createdAt).toLocaleString()}</td><td>{w.status === 'pending' && <button className="small" onClick={() => void update(w, 'processing')}>Process</button>}{w.status === 'processing' && <button className="small" onClick={() => void update(w, 'completed')}>Complete</button>}{['pending', 'processing'].includes(w.status) && <button className="small danger" onClick={() => void update(w, 'failed')}>Fail + refund</button>}</td></tr>)}</tbody></table><Pager page={page} hasMore={rows.length === 50} onChange={setPage} /></section></>; }

function AuditView() { const [logs, setLogs] = useState<Audit[]>([]); const [page, setPage] = useState(0); useEffect(() => { adminFetch<{ logs: Audit[] }>(`/admin/audit-logs?limit=50&offset=${page * 50}`).then((d) => setLogs(d.logs)); }, [page]); return <section className="table-wrap"><table><thead><tr><th>Action</th><th>Admin</th><th>Target</th><th>Time</th></tr></thead><tbody>{logs.map((l) => <tr key={l.id}><td>{l.action}</td><td>{l.adminUser.displayName} <span className="muted">({l.adminUser.role})</span></td><td>{l.targetType ?? '-'} {l.targetId ?? ''}</td><td>{new Date(l.createdAt).toLocaleString()}</td></tr>)}</tbody></table><Pager page={page} hasMore={logs.length === 50} onChange={setPage} /></section>; }

function AdminsView() { const [rows, setRows] = useState<AdminRow[]>([]); const [form, setForm] = useState({ email: '', password: '', displayName: '', role: 'viewer' }); const action = useAction(); const load = () => adminFetch<{ admins: AdminRow[] }>('/admin/admin-users').then((d) => setRows(d.admins)).catch((e) => action.run(async () => { throw e; })); useEffect(() => { void load(); }, []); const create = async (event: FormEvent) => { event.preventDefault(); if (await action.run(() => adminFetch('/admin/admin-users', { method: 'POST', body: JSON.stringify(form) }))) { setForm({ email: '', password: '', displayName: '', role: 'viewer' }); void load(); } }; const toggle = async (row: AdminRow) => { if (await action.run(() => adminFetch(`/admin/admin-users/${row.id}`, { method: 'PATCH', body: JSON.stringify({ status: row.status === 'active' ? 'suspended' : 'active' }) }))) void load(); }; return <><section className="card"><h2>Create administrator</h2><form className="inline-form" onSubmit={create}><input placeholder="Display name" value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} required /><input type="email" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /><input type="password" placeholder="Password (12+ chars)" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required minLength={12} /><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="viewer">Viewer</option><option value="support_admin">Support</option><option value="moderation_admin">Moderation</option><option value="token_admin">Token</option><option value="finance_admin">Finance</option><option value="super_admin">Super admin</option></select><button className="primary">Create</button></form></section><ErrorBox error={action.error} /><section className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Last login</th><th>Action</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td>{r.displayName}</td><td>{r.email}</td><td>{r.role}</td><td>{r.status}</td><td>{r.lastLoginAt ? new Date(r.lastLoginAt).toLocaleString() : 'Never'}</td><td><button className="small" onClick={() => void toggle(r)}>{r.status === 'active' ? 'Suspend' : 'Activate'}</button></td></tr>)}</tbody></table></section></>; }

function Detail({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="modal-backdrop"><section className="modal"><div className="section-title"><h2>{title}</h2><button className="ghost" onClick={onClose}>Close</button></div>{children}</section></div>; }
